/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ReinigungRouteImport } from './routes/reinigung'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKontaktRouteImport } from './routes/api/kontakt'

const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinigungRoute = ReinigungRouteImport.update({
  id: '/reinigung',
  path: '/reinigung',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKontaktRoute = ApiKontaktRouteImport.update({
  id: '/api/kontakt',
  path: '/api/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/kontakt': typeof KontaktRoute
  '/reinigung': typeof ReinigungRoute
  '/security': typeof SecurityRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/kontakt': typeof ApiKontaktRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/kontakt': typeof KontaktRoute
  '/reinigung': typeof ReinigungRoute
  '/security': typeof SecurityRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/kontakt': typeof ApiKontaktRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/kontakt': typeof KontaktRoute
  '/reinigung': typeof ReinigungRoute
  '/security': typeof SecurityRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/kontakt': typeof ApiKontaktRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emails'
    | '/kontakt'
    | '/reinigung'
    | '/security'
    | '/ueber-mich'
    | '/api/kontakt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emails'
    | '/kontakt'
    | '/reinigung'
    | '/security'
    | '/ueber-mich'
    | '/api/kontakt'
  id:
    | '__root__'
    | '/'
    | '/emails'
    | '/kontakt'
    | '/reinigung'
    | '/security'
    | '/ueber-mich'
    | '/api/kontakt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailsRoute: typeof EmailsRoute
  KontaktRoute: typeof KontaktRoute
  ReinigungRoute: typeof ReinigungRoute
  SecurityRoute: typeof SecurityRoute
  UeberMichRoute: typeof UeberMichRoute
  ApiKontaktRoute: typeof ApiKontaktRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinigung': {
      id: '/reinigung'
      path: '/reinigung'
      fullPath: '/reinigung'
      preLoaderRoute: typeof ReinigungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kontakt': {
      id: '/api/kontakt'
      path: '/api/kontakt'
      fullPath: '/api/kontakt'
      preLoaderRoute: typeof ApiKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailsRoute: EmailsRoute,
  KontaktRoute: KontaktRoute,
  ReinigungRoute: ReinigungRoute,
  SecurityRoute: SecurityRoute,
  UeberMichRoute: UeberMichRoute,
  ApiKontaktRoute: ApiKontaktRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
